### ISSUE TITLE
yml config include globals

### ISSUE THREAD

**Issue by knennigtri** [knennigtri/aep-tag-tool#10]
```
Globals:
  SETTINGS_EXT_adobe-target-v2:
    clientCode: xyz
    serverDomain: xyz
    imsOrgId: xyz
  SETTINGS_EXT_adobe-analytics:
    development: xyz
    staging: xzy
    production: xzy
    company: xyz 
    orgId: xyz
    trackingServer
    trackingServerSecure
  SETTINGS_EXT_adobe-mcid
    orgId: xyz
```
