### ISSUE TITLE
Delete should be able to specify searched property

### ISSUE THREAD

**Issue by knennigtri** [knennigtri/aep-tag-tool#22]
Proposal to update the `newsettings` file to be more in line with the json export so it it's easier to read and interpret.

```
extensions:
    - name: adobe-mcid
      settings:
        orgId: "123345@AdobeOrg"
    - name: adobe-target
      settings:
        imsOrgId: "123345@AdobeOrg"
        clientCode: "XXXXXXX"
        serverDomain: "XXXX.tt.omtrdc.net"
    - name: adobe-analytics
      settings:
        orgId: "123345@AdobeOrg"
        company: "XXXXXXX"
        staging: "reportSuiteXXXX"
        production: "reportSuiteXXXX"
        development: "reportSuiteXXXX"
dataElements:
    - name: my.orgID
      settings:
        orgID: "xxxxx"
```
