### ISSUE TITLE
yaml config file for env

### ISSUE THREAD

**Issue by knennigtri** [knennigtri/aep-tag-tool#5]
Rather than asking a user to manually create the env file and globals file, create a simple yaml file that can extract the values and input them into the postman files.... removing the need to understand postman... and opening the door for less dependency on postman

**Comment by knennigtri** [comment]
```
env:
  CLIENT_ID: xzy
  CLIENT_SECRET: xzy
  ORG_ID: xyz
  TECHNICAL_ACCOUNT: xyz
  PRIVATE_KEY: xyz
Globals:
  SETTINGS_EXT_adobe-target-v2:
    clientCode: xyz
    serverDomain: xyz
    imsOrgId: xyz
```
