### ISSUE TITLE
Expand config.yml to support 1+ imports

### ISSUE THREAD

**Issue by knennigtri** [knennigtri/aep-tag-tool#9]
```
---
auth:
 CLIENT_ID: xxxxx
 CLIENT_SECRET: xxxxx
 ORG_ID: xxxxx@AdobeOrg
 TECHNICAL_ACCOUNT: xxxxx@techacct.adobe.com
 PRIVATE_KEY: ./private.key
imports: [
  ./propertyOne.json,
  ./propertyTwo.json
]
---
```
OR
```
---
auth:
 CLIENT_ID: xxxxx
 CLIENT_SECRET: xxxxx
 ORG_ID: xxxxx@AdobeOrg
 TECHNICAL_ACCOUNT: xxxxx@techacct.adobe.com
 PRIVATE_KEY: ./private.key
imports: ./propertyOne.json
---
```
